### ISSUE TITLE
请问SCUPLUS_JOB_CONF这个配置文件能分享一下吗？

### ISSUE THREAD

**Issue by gogobody** [mohuishou/scuplus-go#59]
`panic: Open file error: open : The system cannot find the file specified.

goroutine 1 [running]:
github.com/mohuishou/scuplus-go/job.init.0()
	E:/Projects/we川大/scuplus-go/job/job.go:20 +0x4a8
`

**Comment by mohuishou** [comment]
```yml
broker: 'redis://localhost:6379'
default_queue: machinery_tasks
result_backend: 'redis://localhost:6379'
results_expire_in: 3600
amqp:
  binding_key: machinery_task
  exchange: machinery_exchange
  exchange_type: direct
  prefetch_count: 3
```
